# Main
url:                http://josediazgonzalez.com
title:              Jose Diaz-Gonzalez
author:             Jose Diaz-Gonzalez

# Jekyll Config
# root:         /
permalink:          /:year/:month/:day/:title/
markdown:           rdiscount
pygments:           false
exclude:            README.textile Rakefile
regeneration:       true
lsi:                true

# Custom
related_limit:      5
excerpt_link:       "Read More&hellip;"

# Plugins
disqus_short_name:  josediazgonzalez
ga_tracking_id:     'UA-8668344-3'
category_dir:       categories
code_dir:           code
post_types:
  - portfolio
index_pages:
  category:
    do_related:     false
    title_prefix:   'Category: '
  tag:
    do_related:     true
    title_prefix:   'Tag: '
    