# Site-level configuration. Plugin which require extra
# data should have that in plugin-specific configuration
title:            Jose Diaz-Gonzalez
author:           Jose Diaz-Gonzalez
email:            support@savant.be

# Jekyll Config
# Set this to true to disable plugins
safe:               false
# Enables or disables Jekyll from recreating the site when files are modified.
regeneration:       true
# Fires up a server that will host your _site directory
server:             false
# Changes the port that the Jekyll server will run on
server_port:        4000
# Serve website from a given base URL
baseurl:            /
# Sets site.url, useful for environment switching
url:                http://josediazgonzalez.com

# Changes the directory where Jekyll will look to transform files
source:      .
# Changes the directory where Jekyll will write files to
destination: ./_site
# Changes the directory where Jekyll will look for plugins
plugins:     ./_plugins

# Inclusion/exclusion of future dated posts
future:             true
# Produces an index for related posts. Install rb-gsl and libgsl to speed this up
lsi:                true
# Built-in Code highlighting with Pygments. Disabled because we use a plugin for this
pygments:           false
# Uses [engine] instead of Maruku. Use redcarpet since it's the new hotness
markdown:           redcarpet
# Controls the URLs that posts are generated with.
permalink:          /:year/:month/:day/:title/
# A list of directories and files to exclude from the conversion
exclude:            README.textile Rakefile Gemfile Gemfile.lock requirements.txt

# Rakefile
rakefile:
  site_url:           http://josediazgonzalez.com
  deploy_host:        josediazgonzalez.com
  deploy_path:        /apps/production/josediazgonzalez.com/default/public/_site
  deploy_user:        deploy
  port:               4000
  site:               _site
  editor:             subl

# My custom, layout related stuff
related_limit:      5
excerpt_link:       "Read More&hellip;"
disqus_shortname:  josediazgonzalez
ga_tracking_id:     'UA-8668344-3'

# Plugins
post_types:
  - portfolio
index_pages:
  category:
    do_related:     false
    title_prefix:   'Category: '
  tag:
    do_related:     true
    title_prefix:   'Tag: '
backtick:
  tag:              rainbow
atom:
  title:            Jose Diaz-Gonzalez
  author:           Jose Diaz-Gonzalez
  email:            support@savant.be
