# Main
url:                http://josediazgonzalez.com
title:              Jose Diaz-Gonzalez
author:             Jose Diaz-Gonzalez

# Jekyll Config
# root:         /
permalink:          /:year/:month/:day/:title/
markdown:           redcarpet
pygments:           false
exclude:            README.textile Rakefile Gemfile Gemfile.lock requirements.txt
regeneration:       true
lsi:                true

# Rakefile
# deployed site url for sitemap.xml generator
rakefile:
  site_url:           http://josediazgonzalez.com
  deploy_host:        josediazgonzalez.com
  deploy_path:        /apps/production/josediazgonzalez.com/default/public/_site
  deploy_user:        deploy
  port:               4000
  site:               _site
  editor:             subl


# Custom
related_limit:      5
excerpt_link:       "Read More&hellip;"

# Plugins
disqus_shortname:  josediazgonzalez
ga_tracking_id:     'UA-8668344-3'
code_dir:           code
post_types:
  - portfolio
index_pages:
  category:
    do_related:     false
    title_prefix:   'Category: '
  tag:
    do_related:     true
    title_prefix:   'Tag: '
backtick:
  tag: rainbow