#!/bin/bash

cd ..
mkdir -p stylesheets javascripts _tmp
cat _stylesheets/style.css _stylesheets/font-awesome.css | cleancss -o stylesheets/style-min.css
cat _stylesheets/ie.css | cleancss -o stylesheets/ie-min.css
cat _javascripts/jquery.min.js _javascripts/fancybox/jquery.fancybox-1.3.1.pack.js _javascripts/jquery.easing-1.3.pack.js _javascripts/ui.tabs.min.js _javascripts/jquery.cycle.js _javascripts/rainbow/rainbow.min.js _javascripts/rainbow/languages/c.js _javascripts/rainbow/languages/css.js _javascripts/rainbow/languages/generic.js _javascripts/rainbow/languages/html.js _javascripts/rainbow/languages/javascript.js _javascripts/rainbow/languages/php.js _javascripts/rainbow/languages/python.js _javascripts/rainbow/languages/ruby.js _javascripts/rainbow/languages/shell.js _javascripts/scripts.js > _tmp/scripts.js
uglifyjs -nc _tmp/scripts.js > javascripts/scripts-min.js